### PR TITLE
modify import error, requirements error

### PR DESCRIPTION
**Pull request by hondajojo**

### CODE REVIEW

**Review by chairco — COMMENTED** [review]
I think it no need to add `__init__.py` file.
Just change [file](https://github.com/chairco/2017Talk-Django-crawler-monitor/blob/master/code/pycontw/pycontw/wsgi.py)  content:
```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pycontw.settings")
```
to 
```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "pycontw.settings.local")
```

**Comment by hondajojo** [comment]
if I did not add `__init__.py` file, when I run `python manage.py runserver` , I got an `ImportError: No module named settings.local` error

```
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings.local
```

**Comment by chairco** [comment]
if run on python 3.x also? not sure just guessing.

**Comment by chairco** [comment]
by the way, thanks, aa3c16f, already merge into 35395a6

**Comment by hondajojo** [comment]
you are right, if run on python 3.x, it works. 
I think if I add __init__.py, it will works on python 2.x and python 3.x.

**Comment by chairco** [comment]
Not recommended run 2.x and 3.x same time at Django project, because of there some different here. 
I create runtime.txt file let user know which python run we recommend.

**Comment by hondajojo** [comment]
ok! thanks for previous merges.

**Pull request closed without merging**
